appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MYlTPuhz/JnhVNDG4KnEQtL/Dt8GkwpmSokED9lwIHw9lk4feqsRZgH9IlVoOjOhdu7oWEZr66Mm57lgAeVumea0TUwoCB6TMDeic8+VmKja5TFsO7FYJ52g37mjBsNTUbGjmnBrMN35W3LBaZF/3ny6pGuZ0btM0MgFtYBqtgxiPjskUK1qsXrAhsaw/Ye51ywd17GGxAD9YIG/i/XhePQ3jMG7Z1Igiour4WF49WoAUINwgF/VI2ZC/a98WAsmtenSGaol3WV9ywjiyi+erKOK8D6kEoL0hzhqbA3mYGckt3I5fnQwz7ZRf2xf0HAMBoMlwCS75RArGeyZPJ1MWQN8iWWpFrf3TJsRXMRZ2vp8EBp/DXVooaYsCcUBlwKGv2m0qHOyfMsp2Gif6sd7VA12iPgiwk7gN/07K60ifFqPrSjrBV5GAWWRqd9Pm9Mzkyvg0YB5CRpQDSKKjUmYyGYSU5x3TxxoCj9k82s5a1Vy/d1JW1BtTk304C/bbXLa0tEu54YksUzLKHaXaCXSGh0/hB1cXqSp0TWxWVg5xHD6W36dhBbf2QAFScoWTwjPGGvo+aPU6h/uRLUvq8rZHNtAmVGczmahEb8fLBwMHM+psm4irK3xEKxao0y67NUMvTigHFHXYkmMszFy96IR9xNH8c7/sgJG+4Sjfr0kpNE=}
